# Build sources-final.json — unified source manifest merging base sources.json
# with overlay-specific metadata from sources-overlay.json and data-index.json.
# This is the single authoritative source reference for the model.
# Run: python3 build-sources-overlay.py

import json
import os
from datetime import datetime, timezone

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

BASE = os.path.join(SCRIPT_DIR, "sources.json")
OVERLAY = os.path.join(SCRIPT_DIR, "sources-overlay.json")
INDEX = os.path.join(SCRIPT_DIR, "data-index.json")
OUT = os.path.join(SCRIPT_DIR, "sources-final.json")


def load_json(path):
    with open(path) as f:
        return json.load(f)


def main():
    print("Building sources-final.json")
    print("===========================")
    print()

    base = load_json(BASE)
    overlay = load_json(OVERLAY)
    index = load_json(INDEX)

    # ── Phase 1: Start with base sources ──
    sources = dict(base["sources"])

    # ── Phase 2: Merge overlay metadata for DRI sources ──
    dri_ids = set(overlay["sources"].keys())
    updated = []
    kept = []

    for sid in dri_ids:
        ov_src = overlay["sources"][sid]
        if sid in sources:
            # Merge: keep base fields, add/override with overlay fields
            src = dict(sources[sid])
            for key in ("tier", "tier_note", "extraction_script", "build_script",
                        "overlay_files", "overlay_nutrients", "overlay_groups",
                        "source_files", "limitation", "cross_verified_by",
                        "cross_verification_results", "convention", "format",
                        "description", "authority_note"):
                if key in ov_src:
                    src[key] = ov_src[key]
            # Ensure data_files points to overlay files
            if "overlay_files" in ov_src:
                src["data_files"] = ov_src["overlay_files"]
            sources[sid] = src
            updated.append(sid)
        else:
            # New source not in base (shouldn't happen in practice)
            sources[sid] = dict(ov_src)
            kept.append(sid)

    print(f"  DRI sources merged: {len(updated)} updated, {len(kept)} new")
    for sid in sorted(updated):
        src = sources[sid]
        print(f"    {sid:35s} tier={src.get('tier','?')}  files={src.get('data_files',[])}")
    print()

    # ── Phase 3: Add data-index as a source entry ──
    sources["dietology-data-index"] = {
        "name": "Dietology Data Index — Unified Manifest",
        "tier": "A",
        "category": "manifest",
        "url": None,
        "license": "MIT (project-generated)",
        "mit_compatible": True,
        "format": "JSON — generated by build-data-index.py",
        "authority": "internal",
        "authority_note": "Autogenerated manifest of all knowledge base files. Not a data source — an index of sources and datasets.",
        "update_frequency": "per build",
        "description": "Unified manifest of all dietology knowledge base files with domains, tiers, sources, and statistics. Generated from 6 production datasets.",
        "data_files": ["data-index.json"],
        "extraction_script": None,
        "build_script": "data/build-data-index.py",
        "build_date": index["_meta"]["build_date"]
    }

    # ── Phase 4: Build the final manifest ──
    # Collect stats from data-index
    idx_stats = index["stats"]

    # Count sources by tier
    tiers = {}
    for sid, src in sources.items():
        t = src.get("tier", "?")
        tiers[t] = tiers.get(t, 0) + 1

    # Count sources with overlay_files vs direct data_files
    with_overlay = sum(1 for s in sources.values() if s.get("overlay_files"))
    without_overlay = sum(1 for s in sources.values()
                         if s.get("data_files") and not s.get("overlay_files"))

    output = {
        "_meta": {
            "schema": "sources-final-v1",
            "description": "Unified source manifest — definitive reference for all dietology data sources. Merges base sources.json with overlay-specific metadata from sources-overlay.json and dataset catalog from data-index.json.",
            "build_script": "data/build-sources-overlay.py",
            "build_date": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "input_files": [
                "data/sources.json (base manifest — all sources)",
                "data/sources-overlay.json (DRI overlay metadata)",
                "data/data-index.json (current dataset catalog + stats)",
            ],
            "relationship": "This file is the SINGLE authoritative source reference. sources.json and sources-overlay.json are intermediate inputs — model should load ONLY this file.",
        },
        "schema_version": base["schema_version"],
        "description": base["description"].replace(
            "The model loads this file first",
            "The model loads this file first. THIS IS THE DEFINITIVE VERSION — supersedes sources.json."
        ),
        "sources": sources,
        "gaps": base.get("gaps", {}),

        # ── Overlay catalog (from sources-overlay.json) ──
        "overlay_catalog": overlay.get("overlay_catalog", {}),

        # ── Dataset catalog summary (from data-index.json) ──
        "datasets": index.get("datasets", {}),

        # ── Final stats ──
        "stats": {
            "sources_total": len(sources),
            "sources_by_tier": tiers,
            "sources_with_overlay": with_overlay,
            "sources_direct": without_overlay,
            "dri_nutrients_total": idx_stats.get("total_dri_nutrients", 0),
            "dri_groups_total": idx_stats.get("total_dri_groups", 0),
            "total_foods": idx_stats.get("total_foods", 0),
            "total_lab_tests": idx_stats.get("total_lab_tests", 0),
            "total_diagnostic_thresholds": idx_stats.get("total_diagnostic_thresholds", 0),
            "fabrication": idx_stats.get("fabrication", 0),
            "recalculation": idx_stats.get("recalculation", 0),
        },

        # ── Build pipeline ──
        "build_pipeline": {
            "description": "Full rebuild command — parses source documents, builds overlays, generates index and this manifest.",
            "command": overlay.get("full_rebuild_command", ""),
            "final_step": "python3 data/build-sources-overlay.py",
            "steps": [
                {"step": 1, "script": "data/extract-msd-dri-parser.py", "inputs": 5, "outputs": "*-parsed.json, ncbi-crosscheck.json"},
                {"step": 2, "script": "data/extract-iom-dri.py", "inputs": 1, "outputs": "dri-calcium-iom-2011-parsed.json"},
                {"step": 3, "script": "data/build-minerals-overlay.py", "inputs": 5, "outputs": "dri-minerals-overlay.json"},
                {"step": 4, "script": "data/build-vitamins-overlay.py", "inputs": 2, "outputs": "dri-vitamins-overlay.json"},
                {"step": 5, "script": "data/build-macronutrients-per-kg-overlay.py", "inputs": 2, "outputs": "dri-macronutrients-per-kg-overlay.json"},
                {"step": 6, "script": "data/build-data-index.py", "inputs": 6, "outputs": "data-index.json"},
                {"step": 7, "script": "data/build-sources-overlay.py", "inputs": 3, "outputs": "sources-final.json"},
            ],
        },
    }

    with open(OUT, "w") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    print(f"Written {OUT}")
    print(f"  {len(sources)} sources total")
    print(f"  Tiers: {tiers}")
    print(f"  Overlay sources: {with_overlay}, Direct: {without_overlay}")
    print(f"  DRI: {idx_stats['total_dri_nutrients']} nutrients, {idx_stats['total_dri_groups']} groups")
    print(f"  Datasets indexed: {len(index['datasets'])}")
    print(f"  Build pipeline: {len(output['build_pipeline']['steps'])} steps")

    # Verify
    for sid, src in sources.items():
        assert src.get("name"), f"{sid}: missing name"
        assert src.get("tier") in ("A", "B", "C"), f"{sid}: bad tier {src.get('tier')}"
    print("All assertions passed.")


if __name__ == "__main__":
    main()
